//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Single p_main_maininteract;
        
        private static SteamVR_Action_Boolean p_main_grab;
        
        private static SteamVR_Action_Boolean p_main_secondaryinteract;
        
        private static SteamVR_Action_Pose p_main_pointerpose;
        
        private static SteamVR_Action_Vector2 p_main_scrolling;
        
        private static SteamVR_Action_Skeleton p_main_skeletonlefthand;
        
        private static SteamVR_Action_Skeleton p_main_skeletonrighthand;
        
        private static SteamVR_Action_Vibration p_main_haptics;
        
        public static SteamVR_Action_Single main_maininteract
        {
            get
            {
                return SteamVR_Actions.p_main_maininteract.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean main_grab
        {
            get
            {
                return SteamVR_Actions.p_main_grab.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean main_secondaryinteract
        {
            get
            {
                return SteamVR_Actions.p_main_secondaryinteract.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose main_pointerpose
        {
            get
            {
                return SteamVR_Actions.p_main_pointerpose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vector2 main_scrolling
        {
            get
            {
                return SteamVR_Actions.p_main_scrolling.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Skeleton main_skeletonlefthand
        {
            get
            {
                return SteamVR_Actions.p_main_skeletonlefthand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton main_skeletonrighthand
        {
            get
            {
                return SteamVR_Actions.p_main_skeletonrighthand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Vibration main_haptics
        {
            get
            {
                return SteamVR_Actions.p_main_haptics.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.main_maininteract,
                    SteamVR_Actions.main_grab,
                    SteamVR_Actions.main_secondaryinteract,
                    SteamVR_Actions.main_pointerpose,
                    SteamVR_Actions.main_scrolling,
                    SteamVR_Actions.main_skeletonlefthand,
                    SteamVR_Actions.main_skeletonrighthand,
                    SteamVR_Actions.main_haptics};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.main_maininteract,
                    SteamVR_Actions.main_grab,
                    SteamVR_Actions.main_secondaryinteract,
                    SteamVR_Actions.main_pointerpose,
                    SteamVR_Actions.main_scrolling,
                    SteamVR_Actions.main_skeletonlefthand,
                    SteamVR_Actions.main_skeletonrighthand};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.main_haptics};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.main_haptics};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.main_pointerpose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.main_grab,
                    SteamVR_Actions.main_secondaryinteract};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.main_maininteract};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.main_scrolling};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.main_skeletonlefthand,
                    SteamVR_Actions.main_skeletonrighthand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.main_maininteract,
                    SteamVR_Actions.main_grab,
                    SteamVR_Actions.main_secondaryinteract,
                    SteamVR_Actions.main_scrolling};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_main_maininteract = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/main/in/maininteract")));
            SteamVR_Actions.p_main_grab = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/main/in/grab")));
            SteamVR_Actions.p_main_secondaryinteract = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/main/in/secondaryinteract")));
            SteamVR_Actions.p_main_pointerpose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/main/in/pointerpose")));
            SteamVR_Actions.p_main_scrolling = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/main/in/scrolling")));
            SteamVR_Actions.p_main_skeletonlefthand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/main/in/skeletonlefthand")));
            SteamVR_Actions.p_main_skeletonrighthand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/main/in/skeletonrighthand")));
            SteamVR_Actions.p_main_haptics = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/main/out/haptics")));
        }
    }
}
