//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_main : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single maininteract
        {
            get
            {
                return SteamVR_Actions.main_maininteract;
            }
        }
        
        public virtual SteamVR_Action_Boolean grab
        {
            get
            {
                return SteamVR_Actions.main_grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean secondaryinteract
        {
            get
            {
                return SteamVR_Actions.main_secondaryinteract;
            }
        }
        
        public virtual SteamVR_Action_Vector2 joystick
        {
            get
            {
                return SteamVR_Actions.main_joystick;
            }
        }
        
        public virtual SteamVR_Action_Skeleton skeletonlefthand
        {
            get
            {
                return SteamVR_Actions.main_skeletonlefthand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton skeletonrighthand
        {
            get
            {
                return SteamVR_Actions.main_skeletonrighthand;
            }
        }
        
        public virtual SteamVR_Action_Vibration haptics
        {
            get
            {
                return SteamVR_Actions.main_haptics;
            }
        }
    }
}
